[package]
name = "broker"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.8.19"
serde = { version = "1.0", features = ["derive"] }
rand = "0.9.0-alpha.2"
lazy_static = "1.5.0"
csv = "1.3.0"
chrono = "0.4.38"
serde_json = "1.0.127"
plotters = "0.3.6"
