[package]
name = "analyze"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
statrs = "0.17.1"
ordered-float = "4.2.2"
chrono = "0.4.38"