[package]
name = "rustdll"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "2.10.1"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"

[lib]
name = "rustdll"
# path = "src/hello.rs"
crate-type = ["cdylib"]
